### ISSUE TITLE
AWS bucket is not accessible

### ISSUE THREAD

**Issue by jdidion** [umccr/gridss-purple-linx-nf#36]
```console
$ aws s3 ls s3://umccr-refdata-dev/

An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

**Comment by scwatts** [comment]
Hi @jdidion, the AWS component of this repo and related resources are intended for internal use only. We've since developed [nf-core/oncoanalyser](https://github.com/nf-core/oncoanalyser) that supercedes gridss-purple-linx-nf and is suitable for general use.

**Comment by jdidion** [comment]
Thanks!

**Comment by scwatts** [comment]
No worries, and please let us know if you'd like to discuss anything regarding oncoanalyser analysis or deployment!
