### ISSUE TITLE
Reference data not accessible

### ISSUE THREAD

**Issue by jdidion** [umccr/gridss-purple-linx-nf#37]
This link has expired: https://nextcloud.hartwigmedicalfoundation.nl/s/LTiKTd8XxBqwaiC?path=%2FHMFTools-Resources

**Comment by scwatts** [comment]
Hi @jdidion, thanks for opening the issue - we'll be retiring and archiving this repo soon in preference of [nf-core/oncoanalyser](https://github.com/nf-core/oncoanalyser) so won't make any changes.

If you'd like to access the Hartwig reference data, you can now do so via their [public GCP Bucket](https://console.cloud.google.com/storage/browser/hmf-public).
